#!/usr/bin/env python

# Generated by GPT-5.2 Thinking web UI on 2025-12-22.

import math
from functools import cache


# ---------- Helpers: primes ----------
def primes_up_to(n: int) -> list[int]:
    sieve = bytearray(b"\x01") * (n + 1)
    if n >= 0:
        sieve[0:2] = b"\x00\x00"
    r = int(n**0.5)
    for p in range(2, r + 1):
        if sieve[p]:
            step = p
            start = p * p
            sieve[start : n + 1 : step] = b"\x00" * (((n - start) // step) + 1)
    return [i for i in range(n + 1) if sieve[i]]


# ---------- Core math: H_{a,b} on its genuine turning points ----------
def _normalized(num: int, den: int) -> tuple[int, int]:
    common = math.gcd(num, den)
    return num // common, den // common


def _height(a: int, b: int, point: tuple[int, int]) -> float:
    num, den = point
    if num == 0:
        return 0.0
    if num == den:
        return 1.0

    x = num / den
    z = 0.5 - (b * math.cos(a * math.pi * x) + a * math.cos(b * math.pi * x)) / (
        2.0 * (a + b)
    )

    if z < 0.0 and z > -1e-14:
        return 0.0
    if z > 1.0 and z < 1.0 + 1e-14:
        return 1.0
    return z


def _derivative_interval_sign(
    a: int, b: int, left: tuple[int, int], right: tuple[int, int]
) -> int:
    left_num, left_den = left
    right_num, right_den = right
    x = (left_num * right_den + right_num * left_den) / (2.0 * left_den * right_den)

    value = math.sin((a + b) * math.pi * x * 0.5) * math.cos(
        abs(a - b) * math.pi * x * 0.5
    )
    return 1 if value > 0.0 else -1


@cache
def _turning_values(a: int, b: int) -> tuple[float, ...]:
    """
    Return H(a,b,x) at the true turning points, in x-order.

    The derivative vanishes at candidates from the two factors
    sin((a+b)pi*x/2) and cos((a-b)pi*x/2).  Candidates where the derivative
    keeps the same sign on both sides are tangential zeros, so they are skipped.
    """
    if a <= 0 or b <= 0 or (a & 1) == 0 or (b & 1) == 0:
        raise ValueError("a,b must be positive odd integers")
    if a == b:
        raise ValueError("a != b required")

    s = a + b
    delta = abs(a - b)
    if s % 2 != 0 or delta % 2 != 0:
        raise ValueError("For odd a,b, a+b and |a-b| must be even")

    candidates = [_normalized(2 * k, s) for k in range(s // 2 + 1)]
    candidates.extend(_normalized(2 * k + 1, delta) for k in range(delta // 2))
    points = sorted(set(candidates), key=lambda point: point[0] / point[1])

    interval_signs = [
        _derivative_interval_sign(a, b, points[i], points[i + 1])
        for i in range(len(points) - 1)
    ]
    kept = [points[0]]
    for i in range(1, len(points) - 1):
        if interval_signs[i - 1] != interval_signs[i]:
            kept.append(points[i])
    kept.append(points[-1])

    return tuple(_height(a, b, point) for point in kept)


# ---------- Geometry on the turning-value sequences ----------
def F(a: int, b: int, c: int, d: int) -> float:
    """
    Trace the winding path using only overlaps between monotone height intervals.
    """
    za = _turning_values(a, b)
    zb = _turning_values(c, d)

    i = 0
    j = 0
    current = 0.0
    total = 0.0
    upward = True
    eps = 1e-12

    max_steps = 4 * (len(za) + len(zb)) * (len(za) + len(zb))
    for _ in range(max_steps):
        if i < 0 or i >= len(za) - 1 or j < 0 or j >= len(zb) - 1:
            if abs(current - 1.0) < 1e-9:
                return total
            raise RuntimeError("Winding walk left the valid segment range")

        a0, a1 = za[i], za[i + 1]
        b0, b1 = zb[j], zb[j + 1]
        lower = max(min(a0, a1), min(b0, b1))
        upper = min(max(a0, a1), max(b0, b1))
        nxt = upper if upward else lower

        total += abs(nxt - current)
        advanced = False

        if abs(nxt - a0) <= eps:
            i -= 1
            advanced = True
        elif abs(nxt - a1) <= eps:
            i += 1
            advanced = True

        if abs(nxt - b0) <= eps:
            j -= 1
            advanced = True
        elif abs(nxt - b1) <= eps:
            j += 1
            advanced = True

        if not advanced:
            raise RuntimeError("Winding walk did not hit a segment endpoint")

        current = nxt
        upward = not upward

    raise RuntimeError("Exceeded maximum winding-walk steps")


def G(m: int, n: int) -> float:
    ps = [p for p in primes_up_to(n) if p >= m]
    total = 0.0
    for i, p in enumerate(ps):
        for q in ps[i + 1 :]:
            total += F(p, q, p, 2 * q - p)
    return total


# ---------- Statement checks ----------
# Given:
# F(3,5,3,7) ≈ 7.01772
# F(7,17,9,19) ≈ 26.79578
# G(3,20) ≈ 463.80866
assert abs(F(3, 5, 3, 7) - 7.01772) < 1e-5
assert abs(F(7, 17, 9, 19) - 26.79578) < 1e-5
assert abs(G(3, 20) - 463.80866) < 1e-5


if __name__ == "__main__":
    ans = G(500, 1000)
    print(f"{ans:.5f}")
