#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
LIB_DIR = ROOT / "ProjectEulerSolutions"
EQUIV_DIR = LIB_DIR / "Equiv"
OUTPUT = ROOT / "ProjectEulerSolutions.lean"

IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Kind of sad but apparently you can't have functions without arguments in Lean?
CONST_EQUIV = {"33", "43", "53", "68", "90", "93", "97"}


def module_name(stem: str) -> str:
    if IDENT_RE.match(stem):
        return stem
    return f"«{stem}»"


def sort_key(stem: str):
    if stem.isdigit():
        return (0, int(stem))
    if stem.startswith("P") and stem[1:].isdigit():
        return (0, int(stem[1:]))
    return (1, stem)


def main() -> int:
    lib_stems = [p.stem for p in EQUIV_DIR.glob("P*.lean")]
    lib_stems.sort(key=sort_key)

    lines: list[str] = []
    lines.append("-- This file is autogenerated by generate_lean_toplevel.py; do not edit manually.")
    for stem in lib_stems:
        lines.append(f"import ProjectEulerSolutions.{module_name(stem)}")
        lines.append(f"import ProjectEulerSolutions.Equiv.{module_name(stem)}")

    lines.append("")

    for stem in lib_stems:
        if not stem.startswith("P") or not stem[1:].isdigit():
            continue
        n = stem[1:]
        lhs_expr = f"ProjectEulerStatements.P{n}.naive"
        rhs_expr = f"ProjectEulerSolutions.P{n}.solve"
        lines.append(f"example : {lhs_expr} = {rhs_expr} := by")
        if n in CONST_EQUIV:
            lines.append(f"  exact ProjectEulerSolutions.P{n}.equiv")
        else:
            lines.append("  apply (funext_iff).2")
            lines.append(
                f"  simpa [funext_iff] using ProjectEulerSolutions.P{n}.equiv"
            )
        lines.append("")

    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
